# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 784)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_input = QtWidgets.QFrame(self.frame)
        self.time_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.time_input.setFrameShape(QtWidgets.QFrame.Box)
        self.time_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.time_input.setObjectName("time_input")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.time_input)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.time_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setStyleSheet("background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalScrollBar_1 = QtWidgets.QScrollBar(self.groupBox_4)
        self.verticalScrollBar_1.setMaximumSize(QtCore.QSize(5, 16777215))
        self.verticalScrollBar_1.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
" {\n"
" background-color: #676767;\n"
"}\n"
"\n"
"\n"
"")
        self.verticalScrollBar_1.setMinimum(-80)
        self.verticalScrollBar_1.setMaximum(80)
        self.verticalScrollBar_1.setProperty("value", 0)
        self.verticalScrollBar_1.setTracking(True)
        self.verticalScrollBar_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_1.setObjectName("verticalScrollBar_1")
        self.gridLayout_12.addWidget(self.verticalScrollBar_1, 0, 0, 1, 1)
        self.plot_1 = PlotWidget(self.groupBox_4)
        self.plot_1.setMinimumSize(QtCore.QSize(0, 0))
        self.plot_1.setAutoFillBackground(False)
        self.plot_1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plot_1.setObjectName("plot_1")
        self.gridLayout_12.addWidget(self.plot_1, 0, 1, 1, 1)
        self.horizontalScrollBar_1 = QtWidgets.QScrollBar(self.groupBox_4)
        self.horizontalScrollBar_1.setMaximumSize(QtCore.QSize(16777215, 5))
        self.horizontalScrollBar_1.setStyleSheet("QScrollBar:horizontal {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
" background-color: #676767;\n"
"}\n"
"")
        self.horizontalScrollBar_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_1.setObjectName("horizontalScrollBar_1")
        self.gridLayout_12.addWidget(self.horizontalScrollBar_1, 1, 1, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.SpectrogramBox_1 = QtWidgets.QGroupBox(self.time_input)
        self.SpectrogramBox_1.setEnabled(True)
        self.SpectrogramBox_1.setMinimumSize(QtCore.QSize(350, 200))
        self.SpectrogramBox_1.setMaximumSize(QtCore.QSize(350, 200))
        self.SpectrogramBox_1.setAutoFillBackground(False)
        self.SpectrogramBox_1.setStyleSheet("background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);")
        self.SpectrogramBox_1.setFlat(False)
        self.SpectrogramBox_1.setCheckable(False)
        self.SpectrogramBox_1.setObjectName("SpectrogramBox_1")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.SpectrogramBox_1)
        self.gridLayout_13.setContentsMargins(-1, -1, -1, 2)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.ShowHide_1 = QtWidgets.QCheckBox(self.SpectrogramBox_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShowHide_1.sizePolicy().hasHeightForWidth())
        self.ShowHide_1.setSizePolicy(sizePolicy)
        self.ShowHide_1.setMinimumSize(QtCore.QSize(0, 0))
        self.ShowHide_1.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ShowHide_1.setFont(font)
        self.ShowHide_1.setIconSize(QtCore.QSize(10, 10))
        self.ShowHide_1.setChecked(True)
        self.ShowHide_1.setObjectName("ShowHide_1")
        self.gridLayout_13.addWidget(self.ShowHide_1, 1, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.Spectrogram_1 = QtWidgets.QVBoxLayout()
        self.Spectrogram_1.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.Spectrogram_1.setSpacing(0)
        self.Spectrogram_1.setObjectName("Spectrogram_1")
        self.gridLayout_14.addLayout(self.Spectrogram_1, 0, 0, 1, 2)
        self.gridLayout_13.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.SpectrogramBox_1)
        self.verticalLayout.addWidget(self.time_input)
        self.time_ouput = QtWidgets.QFrame(self.frame)
        self.time_ouput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.time_ouput.setFrameShape(QtWidgets.QFrame.Box)
        self.time_ouput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.time_ouput.setObjectName("time_ouput")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.time_ouput)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_1 = QtWidgets.QGroupBox(self.time_ouput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_1.sizePolicy().hasHeightForWidth())
        self.groupBox_1.setSizePolicy(sizePolicy)
        self.groupBox_1.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_1.setStyleSheet("background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);")
        self.groupBox_1.setObjectName("groupBox_1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.groupBox_1)
        self.verticalScrollBar_2.setMaximumSize(QtCore.QSize(5, 16777215))
        self.verticalScrollBar_2.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
" {\n"
" background-color: #676767;\n"
"}\n"
"\n"
"\n"
"")
        self.verticalScrollBar_2.setMinimum(-80)
        self.verticalScrollBar_2.setMaximum(80)
        self.verticalScrollBar_2.setProperty("value", 0)
        self.verticalScrollBar_2.setTracking(True)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.gridLayout_6.addWidget(self.verticalScrollBar_2, 0, 0, 1, 1)
        self.plot_2 = PlotWidget(self.groupBox_1)
        self.plot_2.setMinimumSize(QtCore.QSize(0, 0))
        self.plot_2.setAutoFillBackground(False)
        self.plot_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plot_2.setObjectName("plot_2")
        self.gridLayout_6.addWidget(self.plot_2, 0, 1, 1, 1)
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(self.groupBox_1)
        self.horizontalScrollBar_2.setMaximumSize(QtCore.QSize(16777215, 5))
        self.horizontalScrollBar_2.setStyleSheet("QScrollBar:horizontal {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
" background-color: #676767;\n"
"}\n"
"")
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.gridLayout_6.addWidget(self.horizontalScrollBar_2, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_1)
        self.SpectrogramBox_2 = QtWidgets.QGroupBox(self.time_ouput)
        self.SpectrogramBox_2.setMinimumSize(QtCore.QSize(350, 200))
        self.SpectrogramBox_2.setMaximumSize(QtCore.QSize(350, 200))
        self.SpectrogramBox_2.setAcceptDrops(False)
        self.SpectrogramBox_2.setStyleSheet("background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);")
        self.SpectrogramBox_2.setObjectName("SpectrogramBox_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.SpectrogramBox_2)
        self.gridLayout_9.setContentsMargins(-1, -1, -1, 2)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Spectrogram_2 = QtWidgets.QVBoxLayout()
        self.Spectrogram_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.Spectrogram_2.setObjectName("Spectrogram_2")
        self.gridLayout_7.addLayout(self.Spectrogram_2, 0, 0, 1, 2)
        self.gridLayout_9.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.ShowHide_2 = QtWidgets.QCheckBox(self.SpectrogramBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShowHide_2.sizePolicy().hasHeightForWidth())
        self.ShowHide_2.setSizePolicy(sizePolicy)
        self.ShowHide_2.setMinimumSize(QtCore.QSize(0, 0))
        self.ShowHide_2.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ShowHide_2.setFont(font)
        self.ShowHide_2.setIconSize(QtCore.QSize(10, 10))
        self.ShowHide_2.setChecked(True)
        self.ShowHide_2.setObjectName("ShowHide_2")
        self.gridLayout_9.addWidget(self.ShowHide_2, 1, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.SpectrogramBox_2)
        self.verticalLayout.addWidget(self.time_ouput)
        self.signal_controls = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signal_controls.sizePolicy().hasHeightForWidth())
        self.signal_controls.setSizePolicy(sizePolicy)
        self.signal_controls.setMaximumSize(QtCore.QSize(16777215, 40))
        self.signal_controls.setFrameShape(QtWidgets.QFrame.Box)
        self.signal_controls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signal_controls.setObjectName("signal_controls")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.signal_controls)
        self.horizontalLayout_8.setContentsMargins(4, 4, 5, 5)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.play_pause_btn = QtWidgets.QPushButton(self.signal_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_pause_btn.sizePolicy().hasHeightForWidth())
        self.play_pause_btn.setSizePolicy(sizePolicy)
        self.play_pause_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.play_pause_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        self.play_pause_btn.setFont(font)
        self.play_pause_btn.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(0, 85, 255);\n"
"color:rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 50, 150);\n"
"}\n"
"")
        self.play_pause_btn.setObjectName("play_pause_btn")
        self.horizontalLayout_8.addWidget(self.play_pause_btn)
        self.ZoomIn = QtWidgets.QPushButton(self.signal_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomIn.sizePolicy().hasHeightForWidth())
        self.ZoomIn.setSizePolicy(sizePolicy)
        self.ZoomIn.setMinimumSize(QtCore.QSize(0, 0))
        self.ZoomIn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ZoomIn.setStyleSheet("")
        self.ZoomIn.setObjectName("ZoomIn")
        self.horizontalLayout_8.addWidget(self.ZoomIn)
        self.ZoomOut = QtWidgets.QPushButton(self.signal_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomOut.sizePolicy().hasHeightForWidth())
        self.ZoomOut.setSizePolicy(sizePolicy)
        self.ZoomOut.setMinimumSize(QtCore.QSize(0, 0))
        self.ZoomOut.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ZoomOut.setStyleSheet("")
        self.ZoomOut.setObjectName("ZoomOut")
        self.horizontalLayout_8.addWidget(self.ZoomOut)
        self.label_13 = QtWidgets.QLabel(self.signal_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        self.label_13.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.speed_slider = QtWidgets.QSlider(self.signal_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed_slider.sizePolicy().hasHeightForWidth())
        self.speed_slider.setSizePolicy(sizePolicy)
        self.speed_slider.setMinimumSize(QtCore.QSize(0, 0))
        self.speed_slider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.speed_slider.setMaximum(8)
        self.speed_slider.setProperty("value", 4)
        self.speed_slider.setTracking(True)
        self.speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.speed_slider.setTickInterval(0)
        self.speed_slider.setObjectName("speed_slider")
        self.horizontalLayout_8.addWidget(self.speed_slider)
        self.reset_btn = QtWidgets.QPushButton(self.signal_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_btn.sizePolicy().hasHeightForWidth())
        self.reset_btn.setSizePolicy(sizePolicy)
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout_8.addWidget(self.reset_btn)
        self.comboBox = QtWidgets.QComboBox(self.signal_controls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.signal_controls)
        self.frequency_output = QtWidgets.QFrame(self.frame)
        self.frequency_output.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frequency_output.setFrameShape(QtWidgets.QFrame.Box)
        self.frequency_output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frequency_output.setObjectName("frequency_output")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frequency_output)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frequency_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setStyleSheet("background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalScrollBar_3 = QtWidgets.QScrollBar(self.groupBox_3)
        self.horizontalScrollBar_3.setMaximumSize(QtCore.QSize(16777215, 5))
        self.horizontalScrollBar_3.setStyleSheet("QScrollBar:horizontal {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
" background-color: #676767;\n"
"}\n"
"")
        self.horizontalScrollBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_3.setInvertedAppearance(False)
        self.horizontalScrollBar_3.setInvertedControls(True)
        self.horizontalScrollBar_3.setObjectName("horizontalScrollBar_3")
        self.gridLayout_11.addWidget(self.horizontalScrollBar_3, 1, 1, 1, 1)
        self.verticalScrollBar_3 = QtWidgets.QScrollBar(self.groupBox_3)
        self.verticalScrollBar_3.setMaximumSize(QtCore.QSize(5, 16777215))
        self.verticalScrollBar_3.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
" {\n"
" background-color: #676767;\n"
"}\n"
"\n"
"\n"
"")
        self.verticalScrollBar_3.setMinimum(-80)
        self.verticalScrollBar_3.setMaximum(80)
        self.verticalScrollBar_3.setProperty("value", 0)
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.gridLayout_11.addWidget(self.verticalScrollBar_3, 0, 0, 1, 1)
        self.plot_3 = PlotWidget(self.groupBox_3)
        self.plot_3.setMinimumSize(QtCore.QSize(0, 0))
        self.plot_3.setAutoFillBackground(False)
        self.plot_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plot_3.setObjectName("plot_3")
        self.gridLayout_11.addWidget(self.plot_3, 0, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.smoothing_box = QtWidgets.QGroupBox(self.frequency_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smoothing_box.sizePolicy().hasHeightForWidth())
        self.smoothing_box.setSizePolicy(sizePolicy)
        self.smoothing_box.setMinimumSize(QtCore.QSize(0, 0))
        self.smoothing_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.smoothing_box.setStyleSheet("background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);")
        self.smoothing_box.setObjectName("smoothing_box")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.smoothing_box)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.plot_5 = PlotWidget(self.smoothing_box)
        self.plot_5.setMinimumSize(QtCore.QSize(0, 0))
        self.plot_5.setAutoFillBackground(False)
        self.plot_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plot_5.setObjectName("plot_5")
        self.gridLayout_8.addWidget(self.plot_5, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.smoothing_box)
        self.verticalLayout.addWidget(self.frequency_output)
        self.freq_sliders = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freq_sliders.sizePolicy().hasHeightForWidth())
        self.freq_sliders.setSizePolicy(sizePolicy)
        self.freq_sliders.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.freq_sliders.setFrameShape(QtWidgets.QFrame.Box)
        self.freq_sliders.setFrameShadow(QtWidgets.QFrame.Raised)
        self.freq_sliders.setObjectName("freq_sliders")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.freq_sliders)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.magnitude_controls = QtWidgets.QGroupBox(self.freq_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnitude_controls.sizePolicy().hasHeightForWidth())
        self.magnitude_controls.setSizePolicy(sizePolicy)
        self.magnitude_controls.setMinimumSize(QtCore.QSize(0, 0))
        self.magnitude_controls.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.magnitude_controls.setStyleSheet("QGroupBox {\n"
"background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QGroupBox::title  {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: -5px 0px 0px 0px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.magnitude_controls.setObjectName("magnitude_controls")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.magnitude_controls)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.magnitude_controls)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalSlider_1 = QtWidgets.QSlider(self.frame_4)
        self.verticalSlider_1.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #fff, stop: 1 #424242\n"
"        );\n"
"    border-radius: 2px;\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    margin: -15px 0px;\n"
"    }\n"
"\n"
"QSlider::handle::hover{\n"
"    border: inset;\n"
"     background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #bbb, stop: 1 #000\n"
"        );\n"
"}")
        self.verticalSlider_1.setMinimum(-5)
        self.verticalSlider_1.setMaximum(5)
        self.verticalSlider_1.setSingleStep(1)
        self.verticalSlider_1.setPageStep(1)
        self.verticalSlider_1.setProperty("value", 0)
        self.verticalSlider_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_1.setTickInterval(0)
        self.verticalSlider_1.setObjectName("verticalSlider_1")
        self.horizontalLayout_2.addWidget(self.verticalSlider_1)
        self.verticalSlider_2 = QtWidgets.QSlider(self.frame_4)
        self.verticalSlider_2.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #fff, stop: 1 #424242\n"
"        );\n"
"    border-radius: 2px;\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    margin: -15px 0px;\n"
"    }\n"
"\n"
"QSlider::handle::hover{\n"
"    border: inset;\n"
"     background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #bbb, stop: 1 #000\n"
"        );\n"
"}")
        self.verticalSlider_2.setMinimum(-5)
        self.verticalSlider_2.setMaximum(5)
        self.verticalSlider_2.setSingleStep(1)
        self.verticalSlider_2.setPageStep(1)
        self.verticalSlider_2.setProperty("value", 0)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_2.setTickInterval(0)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.horizontalLayout_2.addWidget(self.verticalSlider_2)
        self.verticalSlider_3 = QtWidgets.QSlider(self.frame_4)
        self.verticalSlider_3.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #fff, stop: 1 #424242\n"
"        );\n"
"    border-radius: 2px;\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    margin: -15px 0px;\n"
"    }\n"
"\n"
"QSlider::handle::hover{\n"
"    border: inset;\n"
"     background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #bbb, stop: 1 #000\n"
"        );\n"
"}")
        self.verticalSlider_3.setMinimum(-5)
        self.verticalSlider_3.setMaximum(5)
        self.verticalSlider_3.setSingleStep(1)
        self.verticalSlider_3.setPageStep(1)
        self.verticalSlider_3.setProperty("value", 0)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_3.setTickInterval(0)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.horizontalLayout_2.addWidget(self.verticalSlider_3)
        self.verticalSlider_4 = QtWidgets.QSlider(self.frame_4)
        self.verticalSlider_4.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #fff, stop: 1 #424242\n"
"        );\n"
"    border-radius: 2px;\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    margin: -15px 0px;\n"
"    }\n"
"\n"
"QSlider::handle::hover{\n"
"    border: inset;\n"
"     background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #bbb, stop: 1 #000\n"
"        );\n"
"}")
        self.verticalSlider_4.setMinimum(-5)
        self.verticalSlider_4.setMaximum(5)
        self.verticalSlider_4.setPageStep(1)
        self.verticalSlider_4.setProperty("value", 0)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_4.setTickInterval(0)
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.horizontalLayout_2.addWidget(self.verticalSlider_4)
        self.verticalSlider_5 = QtWidgets.QSlider(self.frame_4)
        self.verticalSlider_5.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #fff, stop: 1 #424242\n"
"        );\n"
"    border-radius: 2px;\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    margin: -15px 0px;\n"
"    }\n"
"\n"
"QSlider::handle::hover{\n"
"    border: inset;\n"
"     background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #bbb, stop: 1 #000\n"
"        );\n"
"}")
        self.verticalSlider_5.setMinimum(-5)
        self.verticalSlider_5.setMaximum(5)
        self.verticalSlider_5.setPageStep(1)
        self.verticalSlider_5.setProperty("value", 0)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_5.setTickInterval(0)
        self.verticalSlider_5.setObjectName("verticalSlider_5")
        self.horizontalLayout_2.addWidget(self.verticalSlider_5)
        self.verticalSlider_6 = QtWidgets.QSlider(self.frame_4)
        self.verticalSlider_6.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #fff, stop: 1 #424242\n"
"        );\n"
"    border-radius: 2px;\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    margin: -15px 0px;\n"
"    }\n"
"\n"
"QSlider::handle::hover{\n"
"    border: inset;\n"
"     background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #bbb, stop: 1 #000\n"
"        );\n"
"}")
        self.verticalSlider_6.setMinimum(-5)
        self.verticalSlider_6.setMaximum(5)
        self.verticalSlider_6.setPageStep(1)
        self.verticalSlider_6.setProperty("value", 0)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_6.setTickInterval(0)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        self.horizontalLayout_2.addWidget(self.verticalSlider_6)
        self.verticalSlider_7 = QtWidgets.QSlider(self.frame_4)
        self.verticalSlider_7.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #fff, stop: 1 #424242\n"
"        );\n"
"    border-radius: 2px;\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    margin: -15px 0px;\n"
"    }\n"
"\n"
"QSlider::handle::hover{\n"
"    border: inset;\n"
"     background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #bbb, stop: 1 #000\n"
"        );\n"
"}")
        self.verticalSlider_7.setMinimum(-5)
        self.verticalSlider_7.setMaximum(5)
        self.verticalSlider_7.setPageStep(1)
        self.verticalSlider_7.setProperty("value", 0)
        self.verticalSlider_7.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_7.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_7.setTickInterval(0)
        self.verticalSlider_7.setObjectName("verticalSlider_7")
        self.horizontalLayout_2.addWidget(self.verticalSlider_7)
        self.verticalSlider_8 = QtWidgets.QSlider(self.frame_4)
        self.verticalSlider_8.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #fff, stop: 1 #424242\n"
"        );\n"
"    border-radius: 2px;\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    margin: -15px 0px;\n"
"    }\n"
"\n"
"QSlider::handle::hover{\n"
"    border: inset;\n"
"     background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #bbb, stop: 1 #000\n"
"        );\n"
"}")
        self.verticalSlider_8.setMinimum(-5)
        self.verticalSlider_8.setMaximum(5)
        self.verticalSlider_8.setPageStep(1)
        self.verticalSlider_8.setProperty("value", 0)
        self.verticalSlider_8.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_8.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_8.setTickInterval(0)
        self.verticalSlider_8.setObjectName("verticalSlider_8")
        self.horizontalLayout_2.addWidget(self.verticalSlider_8)
        self.verticalSlider_9 = QtWidgets.QSlider(self.frame_4)
        self.verticalSlider_9.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #fff, stop: 1 #424242\n"
"        );\n"
"    border-radius: 2px;\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    margin: -15px 0px;\n"
"    }\n"
"\n"
"QSlider::handle::hover{\n"
"    border: inset;\n"
"     background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #bbb, stop: 1 #000\n"
"        );\n"
"}")
        self.verticalSlider_9.setMinimum(-5)
        self.verticalSlider_9.setMaximum(5)
        self.verticalSlider_9.setPageStep(1)
        self.verticalSlider_9.setProperty("value", 0)
        self.verticalSlider_9.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_9.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_9.setTickInterval(0)
        self.verticalSlider_9.setObjectName("verticalSlider_9")
        self.horizontalLayout_2.addWidget(self.verticalSlider_9)
        self.verticalSlider_10 = QtWidgets.QSlider(self.frame_4)
        self.verticalSlider_10.setStyleSheet("QSlider{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #fff, stop: 1 #424242\n"
"        );\n"
"    border-radius: 2px;\n"
"    height: 40px;\n"
"    width: 40px;\n"
"    margin: -15px 0px;\n"
"    }\n"
"\n"
"QSlider::handle::hover{\n"
"    border: inset;\n"
"     background-color: qradialgradient(\n"
"        cx: 0.7, cy: 1.4, fx: 0.7, fy: 1.4,\n"
"        radius: 1, stop: 0 #bbb, stop: 1 #000\n"
"        );\n"
"}")
        self.verticalSlider_10.setMinimum(-5)
        self.verticalSlider_10.setMaximum(5)
        self.verticalSlider_10.setPageStep(1)
        self.verticalSlider_10.setProperty("value", 0)
        self.verticalSlider_10.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_10.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_10.setTickInterval(0)
        self.verticalSlider_10.setObjectName("verticalSlider_10")
        self.horizontalLayout_2.addWidget(self.verticalSlider_10)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.magnitude_controls)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_6.addWidget(self.magnitude_controls)
        self.verticalLayout.addWidget(self.freq_sliders)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1069, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuModes = QtWidgets.QMenu(self.menuBar)
        self.menuModes.setObjectName("menuModes")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionUniform_Range_Mode = QtWidgets.QAction(MainWindow)
        self.actionUniform_Range_Mode.setCheckable(True)
        self.actionUniform_Range_Mode.setChecked(True)
        self.actionUniform_Range_Mode.setObjectName("actionUniform_Range_Mode")
        self.actionMusical_Instruments_Mode = QtWidgets.QAction(MainWindow)
        self.actionMusical_Instruments_Mode.setCheckable(True)
        self.actionMusical_Instruments_Mode.setObjectName("actionMusical_Instruments_Mode")
        self.actionAnimals_Sound_Mode = QtWidgets.QAction(MainWindow)
        self.actionAnimals_Sound_Mode.setCheckable(True)
        self.actionAnimals_Sound_Mode.setObjectName("actionAnimals_Sound_Mode")
        self.actionECG_Mode = QtWidgets.QAction(MainWindow)
        self.actionECG_Mode.setCheckable(True)
        self.actionECG_Mode.setObjectName("actionECG_Mode")
        self.actionCall_3asfoor = QtWidgets.QAction(MainWindow)
        self.actionCall_3asfoor.setObjectName("actionCall_3asfoor")
        self.actionPlay_Input = QtWidgets.QAction(MainWindow)
        self.actionPlay_Input.setCheckable(False)
        self.actionPlay_Input.setChecked(False)
        self.actionPlay_Input.setObjectName("actionPlay_Input")
        self.actionPlay_Output = QtWidgets.QAction(MainWindow)
        self.actionPlay_Output.setObjectName("actionPlay_Output")
        self.actionPlay_Input_2 = QtWidgets.QAction(MainWindow)
        self.actionPlay_Input_2.setObjectName("actionPlay_Input_2")
        self.actionPlay_Output_2 = QtWidgets.QAction(MainWindow)
        self.actionPlay_Output_2.setObjectName("actionPlay_Output_2")
        self.menuFile.addAction(self.actionOpen)
        self.menuModes.addAction(self.actionUniform_Range_Mode)
        self.menuModes.addAction(self.actionMusical_Instruments_Mode)
        self.menuModes.addAction(self.actionAnimals_Sound_Mode)
        self.menuModes.addAction(self.actionECG_Mode)
        self.menuHelp.addAction(self.actionCall_3asfoor)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuModes.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Input"))
        self.SpectrogramBox_1.setTitle(_translate("MainWindow", "Spectrogram"))
        self.ShowHide_1.setText(_translate("MainWindow", "Show/Hide"))
        self.groupBox_1.setTitle(_translate("MainWindow", "Output"))
        self.SpectrogramBox_2.setTitle(_translate("MainWindow", "Spectrogram"))
        self.ShowHide_2.setText(_translate("MainWindow", "Show/Hide"))
        self.play_pause_btn.setText(_translate("MainWindow", "Play"))
        self.ZoomIn.setText(_translate("MainWindow", "Zoom In"))
        self.ZoomOut.setText(_translate("MainWindow", "Zoom Out"))
        self.label_13.setText(_translate("MainWindow", "Speed:"))
        self.reset_btn.setText(_translate("MainWindow", "Reset"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Rectangle"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Hamming"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Hanning"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Gaussian"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Frequency"))
        self.smoothing_box.setTitle(_translate("MainWindow", "Smoothing"))
        self.magnitude_controls.setTitle(_translate("MainWindow", "Controls"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuModes.setTitle(_translate("MainWindow", "Modes"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionUniform_Range_Mode.setText(_translate("MainWindow", "Uniform Range Mode"))
        self.actionMusical_Instruments_Mode.setText(_translate("MainWindow", "Musical Instruments Mode"))
        self.actionAnimals_Sound_Mode.setText(_translate("MainWindow", "Animals Sound Mode"))
        self.actionECG_Mode.setText(_translate("MainWindow", "ECG Mode"))
        self.actionCall_3asfoor.setText(_translate("MainWindow", "Call 3asfoor"))
        self.actionPlay_Input.setText(_translate("MainWindow", "Play Input"))
        self.actionPlay_Output.setText(_translate("MainWindow", "Play Output"))
        self.actionPlay_Input_2.setText(_translate("MainWindow", "Play Input"))
        self.actionPlay_Output_2.setText(_translate("MainWindow", "Play Output"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
